name: i18n - Upload Client UI
on:
  workflow_dispatch: null
  schedule:
  - cron: 15 7 * * 1-5
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_CAMPERBOT_SERVICE_TOKEN }}
  CROWDIN_API_URL: https://freecodecamp.crowdin.com/api/v2/
  CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID_ClIENT }}
jobs:
  i18n-upload-client-ui-files:
    name: Client
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Files
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
    - name: Generate Crowdin Config
      uses: freecodecamp/crowdin-action@main
      env:
        PLUGIN: generate-config
        PROJECT_NAME: client
    - name: Crowdin Upload
      uses: crowdin/github-action@master
      with:
        upload_sources: true
        upload_translations: false
        auto_approve_imported: false
        import_eq_suggestions: false
        download_translations: false
        create_pull_request: false
        config: ./crowdin-config.yml
        base_url: ${{ secrets.CROWDIN_BASE_URL_FCC }}
