name: GitHub - Spam PR
on:
  pull_request_target:
    types:
    - labeled
jobs:
  is-spam:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
      with:
        github-token: ${{secrets.CAMPERBOT_NO_TRANSLATE}}
        script: "const isSpam = context.payload.pull_request.labels.find(label =>\
          \ label.name === \"spam\");\nif (isSpam) {\n  github.rest.issues.createComment({\n\
          \    issue_number: context.issue.number,\n    owner: context.repo.owner,\n\
          \    repo: context.repo.repo,\n    body: \"We are marking this pull request\
          \ as spam. Please note that if you are participating in Hacktoberfest, two\
          \ or more PRs marked as spam will result in your permanent disqualification.\\\
          n\\nIf you are interested in making quality and genuine contributions to\
          \ our projects, check out our [contributing guidelines](https://contribute.freecodecamp.org).\"\
          \n  })\n}\n"
